### ISSUE TITLE
error when scanning the qr code

### ISSUE THREAD

**Issue by apaltado** [kaiserdj/Stickerworld#29]
info:     [session:client] Auto close configured to 60s
Error: Evaluation failed: TypeError: Cannot read property 'default' of undefined
    at Object.window.WAPI.window.WAPI.restartService (C:\Users\miteb\OneDrive\Escritorio\!!!\Stickerworld-master\node_modules\venom-bot\dist\lib\wapi\wapi.js:1:57963)
    at __puppeteer_evaluation_script__:1:28
    at ExecutionContext._evaluateInternal (C:\Users\miteb\OneDrive\Escritorio\!!!\Stickerworld-master\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:217:19)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async ExecutionContext.evaluate (C:\Users\miteb\OneDrive\Escritorio\!!!\Stickerworld-master\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:106:16)

**Comment by EncryptedCicada** [comment]
Been facing the same isssue.
output of npm -v = 6.14.11
output of node -v = v14.16.0
My theory is that it's somehow calling for macos specific dependencies on windows. Then again, I could be completely wrong.

**Comment by kaiserdj** [comment]
Sorry for the problems, whatsapp updated the whatsapp web backend and then one of the main libraries of the project was updated, everything was solved in the last commit: https://github.com/kaiserdj/Stickerworld/commit/fe8528a18578461c8f5bfa7a043e98a7056cd864

I close the issue as solved, any problem reopen it or create another
